#!/bin/bash
echo 'downloading git file'
curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
echo 'install unzip'
yum install unzip python -y
echo 'unzip awscli'
unzip awscli-bundle.zip
echo 'if its ubantu server'
#sudo apt-get install unzip - if you dont have unzip in your system
./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
